// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssigmaapi/flnd/v1/flnd.proto

#include "ssigmaapi/flnd/v1/flnd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace ssigmaapi {
namespace flnd {
namespace v1 {
class VitessMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VitessMessage> _instance;
} _VitessMessage_default_instance_;
}  // namespace v1
}  // namespace flnd
}  // namespace ssigmaapi
static void InitDefaultsVitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ssigmaapi::flnd::v1::_VitessMessage_default_instance_;
    new (ptr) ::ssigmaapi::flnd::v1::VitessMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ssigmaapi::flnd::v1::VitessMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto}, {}};

void InitDefaults_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_VitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ssigmaapi::flnd::v1::VitessMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ssigmaapi::flnd::v1::VitessMessage, text_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ssigmaapi::flnd::v1::VitessMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ssigmaapi::flnd::v1::_VitessMessage_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto = {
  {}, AddDescriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, "ssigmaapi/flnd/v1/flnd.proto", schemas,
  file_default_instances, TableStruct_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto::offsets,
  file_level_metadata_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, 1, file_level_enum_descriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, file_level_service_descriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto,
};

const char descriptor_table_protodef_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto[] =
  "\n\034ssigmaapi/flnd/v1/flnd.proto\022\021ssigmaap"
  "i.flnd.v1\032\033google/protobuf/empty.proto\"\035"
  "\n\rVitessMessage\022\014\n\004text\030\001 \001(\t2\302\002\n\017Vitess"
  "ServiceV1\022H\n\nGetMessage\022\026.google.protobu"
  "f.Empty\032 .ssigmaapi.flnd.v1.VitessMessag"
  "e\"\000\022K\n\rCreateMessage\022 .ssigmaapi.flnd.v1"
  ".VitessMessage\032\026.google.protobuf.Empty\"\000"
  "\022K\n\rUpdateMessage\022 .ssigmaapi.flnd.v1.Vi"
  "tessMessage\032\026.google.protobuf.Empty\"\000\022K\n"
  "\rDeleteMessage\022 .ssigmaapi.flnd.v1.Vites"
  "sMessage\032\026.google.protobuf.Empty\"\000B.Z,gi"
  "thub.com/sansigma/ssigmaapigo/flnd/v1;fl"
  "ndb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto = {
  false, InitDefaults_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, 
  descriptor_table_protodef_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto,
  "ssigmaapi/flnd/v1/flnd.proto", &assign_descriptors_table_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, 490,
};

void AddDescriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fempty_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto = []() { AddDescriptors_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto(); return true; }();
namespace ssigmaapi {
namespace flnd {
namespace v1 {

// ===================================================================

void VitessMessage::InitAsDefaultInstance() {
}
class VitessMessage::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VitessMessage::kTextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VitessMessage::VitessMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ssigmaapi.flnd.v1.VitessMessage)
}
VitessMessage::VitessMessage(const VitessMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.text().size() > 0) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  // @@protoc_insertion_point(copy_constructor:ssigmaapi.flnd.v1.VitessMessage)
}

void VitessMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_VitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto.base);
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

VitessMessage::~VitessMessage() {
  // @@protoc_insertion_point(destructor:ssigmaapi.flnd.v1.VitessMessage)
  SharedDtor();
}

void VitessMessage::SharedDtor() {
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void VitessMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VitessMessage& VitessMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_VitessMessage_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto.base);
  return *internal_default_instance();
}


void VitessMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ssigmaapi.flnd.v1.VitessMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* VitessMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<VitessMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string text = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ssigmaapi.flnd.v1.VitessMessage.text");
        object = msg->mutable_text();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool VitessMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ssigmaapi.flnd.v1.VitessMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string text = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text().data(), static_cast<int>(this->text().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ssigmaapi.flnd.v1.VitessMessage.text"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ssigmaapi.flnd.v1.VitessMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ssigmaapi.flnd.v1.VitessMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void VitessMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ssigmaapi.flnd.v1.VitessMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ssigmaapi.flnd.v1.VitessMessage.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->text(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ssigmaapi.flnd.v1.VitessMessage)
}

::google::protobuf::uint8* VitessMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ssigmaapi.flnd.v1.VitessMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ssigmaapi.flnd.v1.VitessMessage.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->text(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ssigmaapi.flnd.v1.VitessMessage)
  return target;
}

size_t VitessMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ssigmaapi.flnd.v1.VitessMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 1;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->text());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VitessMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ssigmaapi.flnd.v1.VitessMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const VitessMessage* source =
      ::google::protobuf::DynamicCastToGenerated<VitessMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ssigmaapi.flnd.v1.VitessMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ssigmaapi.flnd.v1.VitessMessage)
    MergeFrom(*source);
  }
}

void VitessMessage::MergeFrom(const VitessMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ssigmaapi.flnd.v1.VitessMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
}

void VitessMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ssigmaapi.flnd.v1.VitessMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VitessMessage::CopyFrom(const VitessMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ssigmaapi.flnd.v1.VitessMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VitessMessage::IsInitialized() const {
  return true;
}

void VitessMessage::Swap(VitessMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VitessMessage::InternalSwap(VitessMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  text_.Swap(&other->text_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata VitessMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto);
  return ::file_level_metadata_ssigmaapi_2fflnd_2fv1_2fflnd_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace flnd
}  // namespace ssigmaapi
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::ssigmaapi::flnd::v1::VitessMessage* Arena::CreateMaybeMessage< ::ssigmaapi::flnd::v1::VitessMessage >(Arena* arena) {
  return Arena::CreateInternal< ::ssigmaapi::flnd::v1::VitessMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
