// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssigmaapi/hoge.proto

#include "ssigmaapi/hoge.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace ssigmaapi {
namespace type {
class HogeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Hoge>
      _instance;
} _Hoge_default_instance_;
}  // namespace type
}  // namespace ssigmaapi
namespace protobuf_ssigmaapi_2fhoge_2eproto {
static void InitDefaultsHoge() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ssigmaapi::type::_Hoge_default_instance_;
    new (ptr) ::ssigmaapi::type::Hoge();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ssigmaapi::type::Hoge::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Hoge =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsHoge}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Hoge.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ssigmaapi::type::Hoge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ssigmaapi::type::Hoge, huga_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ssigmaapi::type::Hoge)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ssigmaapi::type::_Hoge_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ssigmaapi/hoge.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024ssigmaapi/hoge.proto\022\016ssigmaapi.type\"\024"
      "\n\004Hoge\022\014\n\004huga\030\001 \001(\tB$Z\"github.com/kaito"
      "2/ssigmaapigo;hogeb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 106);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ssigmaapi/hoge.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ssigmaapi_2fhoge_2eproto
namespace ssigmaapi {
namespace type {

// ===================================================================

void Hoge::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Hoge::kHugaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Hoge::Hoge()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ssigmaapi_2fhoge_2eproto::scc_info_Hoge.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ssigmaapi.type.Hoge)
}
Hoge::Hoge(const Hoge& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  huga_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.huga().size() > 0) {
    huga_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.huga_);
  }
  // @@protoc_insertion_point(copy_constructor:ssigmaapi.type.Hoge)
}

void Hoge::SharedCtor() {
  huga_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Hoge::~Hoge() {
  // @@protoc_insertion_point(destructor:ssigmaapi.type.Hoge)
  SharedDtor();
}

void Hoge::SharedDtor() {
  huga_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Hoge::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Hoge::descriptor() {
  ::protobuf_ssigmaapi_2fhoge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssigmaapi_2fhoge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Hoge& Hoge::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ssigmaapi_2fhoge_2eproto::scc_info_Hoge.base);
  return *internal_default_instance();
}


void Hoge::Clear() {
// @@protoc_insertion_point(message_clear_start:ssigmaapi.type.Hoge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  huga_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Hoge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ssigmaapi.type.Hoge)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string huga = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_huga()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->huga().data(), static_cast<int>(this->huga().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ssigmaapi.type.Hoge.huga"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ssigmaapi.type.Hoge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ssigmaapi.type.Hoge)
  return false;
#undef DO_
}

void Hoge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ssigmaapi.type.Hoge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string huga = 1;
  if (this->huga().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->huga().data(), static_cast<int>(this->huga().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ssigmaapi.type.Hoge.huga");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->huga(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ssigmaapi.type.Hoge)
}

::google::protobuf::uint8* Hoge::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ssigmaapi.type.Hoge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string huga = 1;
  if (this->huga().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->huga().data(), static_cast<int>(this->huga().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ssigmaapi.type.Hoge.huga");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->huga(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ssigmaapi.type.Hoge)
  return target;
}

size_t Hoge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ssigmaapi.type.Hoge)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string huga = 1;
  if (this->huga().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->huga());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Hoge::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ssigmaapi.type.Hoge)
  GOOGLE_DCHECK_NE(&from, this);
  const Hoge* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Hoge>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ssigmaapi.type.Hoge)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ssigmaapi.type.Hoge)
    MergeFrom(*source);
  }
}

void Hoge::MergeFrom(const Hoge& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ssigmaapi.type.Hoge)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.huga().size() > 0) {

    huga_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.huga_);
  }
}

void Hoge::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ssigmaapi.type.Hoge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Hoge::CopyFrom(const Hoge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ssigmaapi.type.Hoge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Hoge::IsInitialized() const {
  return true;
}

void Hoge::Swap(Hoge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Hoge::InternalSwap(Hoge* other) {
  using std::swap;
  huga_.Swap(&other->huga_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Hoge::GetMetadata() const {
  protobuf_ssigmaapi_2fhoge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ssigmaapi_2fhoge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace type
}  // namespace ssigmaapi
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ssigmaapi::type::Hoge* Arena::CreateMaybeMessage< ::ssigmaapi::type::Hoge >(Arena* arena) {
  return Arena::CreateInternal< ::ssigmaapi::type::Hoge >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
